"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ESROBJECT(object):
    __slots__ = ["m_objtype", "m_vertical", "m_horizon", "m_vertical_velocity", "m_horizon_velocity", "m_width"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.m_objtype = 0
        self.m_vertical = 0.0
        self.m_horizon = 0.0
        self.m_vertical_velocity = 0.0
        self.m_horizon_velocity = 0.0
        self.m_width = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ESROBJECT._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">Bfffff", self.m_objtype, self.m_vertical, self.m_horizon, self.m_vertical_velocity, self.m_horizon_velocity, self.m_width))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ESROBJECT._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ESROBJECT._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ESROBJECT()
        self.m_objtype, self.m_vertical, self.m_horizon, self.m_vertical_velocity, self.m_horizon_velocity, self.m_width = struct.unpack(">Bfffff", buf.read(21))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ESROBJECT in parents: return 0
        tmphash = (0x9ce28478fefc1827) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ESROBJECT._packed_fingerprint is None:
            ESROBJECT._packed_fingerprint = struct.pack(">Q", ESROBJECT._get_hash_recursive([]))
        return ESROBJECT._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

