"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MsgRainDetectionSignal(object):
    __slots__ = ["timestamp", "rain_signal"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.rain_signal = 0

    def encode(self):
        buf = BytesIO()
        buf.write(MsgRainDetectionSignal._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qB", self.timestamp, self.rain_signal))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MsgRainDetectionSignal._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MsgRainDetectionSignal._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MsgRainDetectionSignal()
        self.timestamp, self.rain_signal = struct.unpack(">qB", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MsgRainDetectionSignal in parents: return 0
        tmphash = (0x6e3f188f211f9986) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MsgRainDetectionSignal._packed_fingerprint is None:
            MsgRainDetectionSignal._packed_fingerprint = struct.pack(">Q", MsgRainDetectionSignal._get_hash_recursive([]))
        return MsgRainDetectionSignal._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

