"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class MsgTrafficLightSignal(object):
    __slots__ = ["timestamp", "left", "forward", "right"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.left = False
        self.forward = False
        self.right = False

    def encode(self):
        buf = BytesIO()
        buf.write(MsgTrafficLightSignal._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbbb", self.timestamp, self.left, self.forward, self.right))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != MsgTrafficLightSignal._get_packed_fingerprint():
            raise ValueError("Decode error")
        return MsgTrafficLightSignal._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = MsgTrafficLightSignal()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.left = bool(struct.unpack('b', buf.read(1))[0])
        self.forward = bool(struct.unpack('b', buf.read(1))[0])
        self.right = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if MsgTrafficLightSignal in parents: return 0
        tmphash = (0x5564723f83885d01) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if MsgTrafficLightSignal._packed_fingerprint is None:
            MsgTrafficLightSignal._packed_fingerprint = struct.pack(">Q", MsgTrafficLightSignal._get_hash_recursive([]))
        return MsgTrafficLightSignal._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

