"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from LinePoint import LinePoint

class StopLine(object):
    __slots__ = ["exist", "num", "stop_points", "distance"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.exist = False
        self.num = 0
        self.stop_points = []
        self.distance = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(StopLine._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bi", self.exist, self.num))
        for i0 in range(self.num):
            assert self.stop_points[i0]._get_packed_fingerprint() == LinePoint._get_packed_fingerprint()
            self.stop_points[i0]._encode_one(buf)
        buf.write(struct.pack(">f", self.distance))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != StopLine._get_packed_fingerprint():
            raise ValueError("Decode error")
        return StopLine._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = StopLine()
        self.exist = bool(struct.unpack('b', buf.read(1))[0])
        self.num = struct.unpack(">i", buf.read(4))[0]
        self.stop_points = []
        for i0 in range(self.num):
            self.stop_points.append(LinePoint._decode_one(buf))
        self.distance = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if StopLine in parents: return 0
        newparents = parents + [StopLine]
        tmphash = (0x6e705f78a422b12d+ LinePoint._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if StopLine._packed_fingerprint is None:
            StopLine._packed_fingerprint = struct.pack(">Q", StopLine._get_hash_recursive([]))
        return StopLine._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

