"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from TrajectoryPoint import TrajectoryPoint

class structAIMPATH(object):
    __slots__ = ["num_points", "points"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.num_points = 0
        self.points = []

    def encode(self):
        buf = BytesIO()
        buf.write(structAIMPATH._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_points))
        for i0 in range(self.num_points):
            assert self.points[i0]._get_packed_fingerprint() == TrajectoryPoint._get_packed_fingerprint()
            self.points[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structAIMPATH._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structAIMPATH._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structAIMPATH()
        self.num_points = struct.unpack(">i", buf.read(4))[0]
        self.points = []
        for i0 in range(self.num_points):
            self.points.append(TrajectoryPoint._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structAIMPATH in parents: return 0
        newparents = parents + [structAIMPATH]
        tmphash = (0xd8a5d60bdf5d384+ TrajectoryPoint._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structAIMPATH._packed_fingerprint is None:
            structAIMPATH._packed_fingerprint = struct.pack(">Q", structAIMPATH._get_hash_recursive([]))
        return structAIMPATH._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

