"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class structSLAMCONTROL(object):
    __slots__ = ["mapping"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.mapping = 0

    def encode(self):
        buf = BytesIO()
        buf.write(structSLAMCONTROL._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">B", self.mapping))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structSLAMCONTROL._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structSLAMCONTROL._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structSLAMCONTROL()
        self.mapping = struct.unpack(">B", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structSLAMCONTROL in parents: return 0
        tmphash = (0xd2638f4c8bf577b2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structSLAMCONTROL._packed_fingerprint is None:
            structSLAMCONTROL._packed_fingerprint = struct.pack(">Q", structSLAMCONTROL._get_hash_recursive([]))
        return structSLAMCONTROL._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

