"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from ESROBJECT import ESROBJECT

class structESROBJINFO(object):
    __slots__ = ["timestamp", "objects", "m_number_objs"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.timestamp = 0
        self.objects = [ ESROBJECT() for dim0 in range(64) ]
        self.m_number_objs = 0

    def encode(self):
        buf = BytesIO()
        buf.write(structESROBJINFO._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        for i0 in range(64):
            assert self.objects[i0]._get_packed_fingerprint() == ESROBJECT._get_packed_fingerprint()
            self.objects[i0]._encode_one(buf)
        buf.write(struct.pack(">b", self.m_number_objs))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structESROBJINFO._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structESROBJINFO._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structESROBJINFO()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.objects = []
        for i0 in range(64):
            self.objects.append(ESROBJECT._decode_one(buf))
        self.m_number_objs = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structESROBJINFO in parents: return 0
        newparents = parents + [structESROBJINFO]
        tmphash = (0x7b8c5421d1885dc4+ ESROBJECT._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structESROBJINFO._packed_fingerprint is None:
            structESROBJINFO._packed_fingerprint = struct.pack(">Q", structESROBJINFO._get_hash_recursive([]))
        return structESROBJINFO._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

