"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pt(object):
    __slots__ = ["x_", "y_", "z_"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.x_ = 0.0
        self.y_ = 0.0
        self.z_ = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(pt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.x_, self.y_, self.z_))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pt()
        self.x_, self.y_, self.z_ = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pt in parents: return 0
        tmphash = (0xfddbdae5ab8c62a6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pt._packed_fingerprint is None:
            pt._packed_fingerprint = struct.pack(">Q", pt._get_hash_recursive([]))
        return pt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

