"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import icumsg_lcm.pt

class structPCLOUD(object):
    __slots__ = ["pnum", "clouddata"]

    __typenames__ = ["int64_t", "icumsg_lcm.pt"]

    __dimensions__ = [None, ["pnum"]]

    def __init__(self):
        self.pnum = 0
        self.clouddata = []

    def encode(self):
        buf = BytesIO()
        buf.write(structPCLOUD._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.pnum))
        for i0 in range(self.pnum):
            assert self.clouddata[i0]._get_packed_fingerprint() == icumsg_lcm.pt._get_packed_fingerprint()
            self.clouddata[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structPCLOUD._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structPCLOUD._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structPCLOUD()
        self.pnum = struct.unpack(">q", buf.read(8))[0]
        self.clouddata = []
        for i0 in range(self.pnum):
            self.clouddata.append(icumsg_lcm.pt._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structPCLOUD in parents: return 0
        newparents = parents + [structPCLOUD]
        tmphash = (0x5e313cd47cffb4ab+ icumsg_lcm.pt._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structPCLOUD._packed_fingerprint is None:
            structPCLOUD._packed_fingerprint = struct.pack(">Q", structPCLOUD._get_hash_recursive([]))
        return structPCLOUD._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

