"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class structSTOPLINE(object):
    __slots__ = ["timestamp", "fDist"]

    __typenames__ = ["int64_t", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        self.fDist = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(structSTOPLINE._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qf", self.timestamp, self.fDist))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structSTOPLINE._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structSTOPLINE._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structSTOPLINE()
        self.timestamp, self.fDist = struct.unpack(">qf", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structSTOPLINE in parents: return 0
        tmphash = (0xcd7fd0673404ea88) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structSTOPLINE._packed_fingerprint is None:
            structSTOPLINE._packed_fingerprint = struct.pack(">Q", structSTOPLINE._get_hash_recursive([]))
        return structSTOPLINE._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

