"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class structCANCONTROLZLG(object):
    __slots__ = ["timestamp", "throttle", "steer", "brake", "reverse"]

    __typenames__ = ["int64_t", "double", "double", "double", "boolean"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.throttle = 0.0
        self.steer = 0.0
        self.brake = 0.0
        self.reverse = False

    def encode(self):
        buf = BytesIO()
        buf.write(structCANCONTROLZLG._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddb", self.timestamp, self.throttle, self.steer, self.brake, self.reverse))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != structCANCONTROLZLG._get_packed_fingerprint():
            raise ValueError("Decode error")
        return structCANCONTROLZLG._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = structCANCONTROLZLG()
        self.timestamp, self.throttle, self.steer, self.brake = struct.unpack(">qddd", buf.read(32))
        self.reverse = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if structCANCONTROLZLG in parents: return 0
        tmphash = (0x526cee9570aae8f6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if structCANCONTROLZLG._packed_fingerprint is None:
            structCANCONTROLZLG._packed_fingerprint = struct.pack(">Q", structCANCONTROLZLG._get_hash_recursive([]))
        return structCANCONTROLZLG._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

