"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class namedMapArray(object):
    __slots__ = ["name", "cells"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.name = ""
        self.cells = [ "" for dim0 in range(401) ]

    def encode(self):
        buf = BytesIO()
        buf.write(namedMapArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        for i0 in range(401):
            buf.write(bytearray(self.cells[i0][:151]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != namedMapArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return namedMapArray._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = namedMapArray()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.cells = []
        for i0 in range(401):
            self.cells.append(buf.read(151))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if namedMapArray in parents: return 0
        tmphash = (0xf7a9b5bde2acbf3d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if namedMapArray._packed_fingerprint is None:
            namedMapArray._packed_fingerprint = struct.pack(">Q", namedMapArray._get_hash_recursive([]))
        return namedMapArray._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

