"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class point3d(object):
    __slots__ = ["px_", "py_", "pz_"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.px_ = 0.0
        self.py_ = 0.0
        self.pz_ = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(point3d._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.px_, self.py_, self.pz_))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != point3d._get_packed_fingerprint():
            raise ValueError("Decode error")
        return point3d._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = point3d()
        self.px_, self.py_, self.pz_ = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if point3d in parents: return 0
        tmphash = (0x8b7aac768854bf32) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if point3d._packed_fingerprint is None:
            point3d._packed_fingerprint = struct.pack(">Q", point3d._get_hash_recursive([]))
        return point3d._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

